SELECT * FROM books_for_pc WHERE Price IS NULL OR Price=0;
SELECT * FROM books_for_pc WHERE Price IS NOT NULL AND Tirage IS NULL;
SELECT * FROM books_for_pc WHERE Date_book IS NULL;
SELECT * FROM books_for_pc WHERE DATEDIFF(CURRENT_DATE,Date_book)<365;
SELECT * FROM books_for_pc WHERE Is_new=True ORDER BY Price ASC;
SELECT * FROM books_for_pc WHERE Pages_count BETWEEN 300 AND 400 ORDER BY Name DESC;
SELECT * FROM books_for_pc WHERE Price BETWEEN 20 AND 40 ORDER BY Date_book DESC;
SELECT * FROM books_for_pc ORDER BY Name ASC,Price DESC;
SELECT * FROM books_for_pc WHERE (Price/Pages_count)<0.1;
SELECT LENGTH(Name), UPPER(LEFT(Name,20)) FROM books_for_pc;
SELECT CONCAT(UPPER(LEFT(Name,10)),'...',UPPER(RIGHT(Name,10))) FROM books_for_pc;
SELECT Name, Date_book, DAY(Date_book), MONTH(Date_book), YEAR(Date_book) FROM books_for_pc;
SELECT Name, Date_book, concat(DAY(date_book),'/',MONTH(date_book),'/',YEAR(date_book)) FROM books_for_pc;
SELECT Code, Price,Price*36.2 AS HRN ,Price*0.9 AS EUR, Price*75.25 AS RUB FROM books_for_pc;
SELECT Code, Price, truncate(Price*29.42,0), round(Price,0) FROM  books_for_pc;
INSERT INTO books_for_pc(N, Code, Is_new, Name, Price, Publisher, Pages_count, Format, Date_book, Tirage, Theme, Category) VALUES (3222,333,TRUE,'BOOK  333',31.00,'RUSLAN NAGNIBEDA',453,'123/324X23','2022-04-03',3400,'XXXXX','XXXX');
INSERT INTO books_for_pc (N, Code, Name, Price, Publisher, Theme, Category) VALUES (232,321,'BOOK 12',12.00,'RUSLAN ANGIBEDA', 'XXXX','XXXX');
DELETE FROM books_for_pc WHERE YEAR(Date_book)<1990;
UPDATE books_for_pc SET Date_book = CURRENT_DATE WHERE Date_book IS NULL;
UPDATE books_for_pc SET Is_new=TRUE WHERE YEAR(Date_book)>=2005;