SELECT COUNT(N),SUM(Price),SUM(Price)/COUNT(N),MIN(Price),MAX(Price) from books_for_pc;
SELECT COUNT(N) from books_for_pc WHERE Price IS NOT NULL;
SELECT COUNT(N),SUM(Price),SUM(Price)/COUNT(N),MIN(Price),MAX(Price) from books_for_pc GROUP BY Is_new;
SELECT COUNT(N),SUM(Price),SUM(Price)/COUNT(N),MIN(Price),MAX(Price) from books_for_pc GROUP BY YEAR(Date_book);
SELECT COUNT(N),SUM(Price),SUM(Price)/COUNT(N),MIN(Price),MAX(Price) from books_for_pc WHERE Price NOT BETWEEN 20 AND 30 GROUP BY YEAR(Date_book);
SELECT COUNT(N),SUM(Price),SUM(Price)/COUNT(N),MIN(Price),MAX(Price) from books_for_pc WHERE Price NOT BETWEEN 20 AND 30 GROUP BY YEAR(Date_book) DESC;
SELECT COUNT(Code) , COUNT(DISTINCT Code) FROM books_for_pc;
SELECT COUNT(N),SUM(Price) FROM books_for_pc GROUP BY LEFT(Name,1);
SELECT COUNT(N),SUM(Price) FROM books_for_pc WHERE LEFT(Name,1) NOT REGEXP'[A-Za-z0-9]' GROUP BY LEFT(Name,1);
SELECT COUNT(N),SUM(Price) FROM books_for_pc WHERE LEFT(Name,1) NOT REGEXP'[A-Za-z0-9]' AND YEAR(Date_book)>2000 GROUP BY LEFT(Name,1);
SELECT COUNT(N),SUM(Price) FROM books_for_pc WHERE LEFT(Name,1) NOT REGEXP'[A-Za-z0-9]' AND YEAR(Date_book)>2000 GROUP BY LEFT(Name,1) DESC;
SELECT COUNT(N),SUM(Price),SUM(Price)/COUNT(N),MIN(Price),MAX(Price) from books_for_pc GROUP BY MONTH(Date_book),YEAR(Date_book);
SELECT COUNT(N),SUM(Price),SUM(Price)/COUNT(N),MIN(Price),MAX(Price) from books_for_pc WHERE Date_book IS NOT NULL GROUP BY MONTH(Date_book),YEAR(Date_book);
SELECT COUNT(N),SUM(Price),SUM(Price)/COUNT(N),MIN(Price),MAX(Price) from books_for_pc GROUP BY MONTH(Date_book) ASC,YEAR(Date_book) DESC;
SELECT Is_new AS 'нова',SUM(Price) AS 'Загальна ціна', SUM(Price)*36.8 AS 'Загальна ціна в грн.',SUM(Price)*0.9 AS 'Загальа ціна в євро',SUM(Price)*70.5 AS 'Загальна ціна в руб' FROM books_for_pc GROUP BY Is_new;
SELECT Is_new AS 'нова',ROUND(SUM(Price),0) AS 'Загальна ціна', ROUND(SUM(Price)*36.8,0) AS 'Загальна ціна в грн.',ROUND(SUM(Price)*0.9,0) AS 'Загальа ціна в євро',ROUND(SUM(Price)*70.5,0) AS 'Загальна ціна в руб' FROM books_for_pc GROUP BY Is_new;
SELECT COUNT(N),SUM(Price),SUM(Price)/COUNT(N),MIN(Price),MAX(Price) from books_for_pc GROUP BY Publisher;
SELECT COUNT(N),SUM(Price),SUM(Price)/COUNT(N),MIN(Price),MAX(Price) from books_for_pc GROUP BY Publisher,Theme;
SELECT COUNT(N),SUM(Price),SUM(Price)/COUNT(N),MIN(Price),MAX(Price) from books_for_pc GROUP BY Publisher,Theme,Category;
SELECT * FROM books_for_pc WHERE (ROUND(Price,0)/Pages_count)>0.1;